### ISSUE TITLE
Create step extension for Choice

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/step-extension-repository#1]
We need a more comprehensive way of editing `choice`:

https://github.com/KaotoIO/camel-component-metadata/blob/main/message-router-choice.camel-component.yaml

**Comment by igarashitm** [comment]
I'll look into as it's needed to complete KaotoIO/kaoto-ui#1080

**Comment by igarashitm** [comment]
![choice-step-extension](https://user-images.githubusercontent.com/265462/222271153-1376fe5d-36d9-4091-ad60-e1139a5610ae.gif)
